### PR TITLE
Added transmitter implementation.

### PR DESCRIPTION
**Pull request by crondaemon**
Added transmitter implementation, taken from freerange previous abandoned fork. Code seems to be portable just copying files. Implementation has been tested with a professional SMPP simulator.

### CODE REVIEW

**Comment by raykrueger** [comment]
Sorry, I just reverted this change.
I just clicked the merge button in the UI without really looking at the code. This code does not take in any of the refactoring that was done in master. This is why the freerange branch ended up the way it is as well unfortunately.

If you could tackle the refactoring that would be awesome, I'd love to pull that in. As it is now there's a bunch of duplicate code between that Transmitter and the Smpp::Base.

**Comment by crondaemon** [comment]
Well known, I will have a look at the code soon. I will send you a new pull
request asap.
Feel free to reject my request until it is ok. I really want to have
transmitter code in master, this will help me so much in my production code.

**Comment by crondaemon** [comment]
Hi Ray
I had a look at the code. I found some duplicate code... but not so much.
I have pushed revised code on my fork. If you are so kind to have a look at
it, I can work on it before requesting the pull.
Hope to have understood what you meant, otherside give me clues about what
code needs improvement.
Thanks!
Dario.

**Comment by crondaemon** [comment]
Hi Ray
I'm very sorry, I didn't read your comment when you reverted the pull
request.
Now I've moved the code from Transmitter::process_pdu() to
Base::process_pdu(). Hope it helps the merge.
Dario.

**Pull request merged**
