### PR TITLE
Multiple changes (remove encoding logic, introduce transmitter, add udh support, tidy some tests)

### PR DESCRIPTION
**Pull request by chrisroos**
Changes (as copied from the email last night):
- We've removed all encoding logic from Smpp::Pdu::DeliverSm. After changing the encoding logic based on the requirements of our SMSC we realised that it was probably best that this be handled outside of the library. I notice that you've extracted a utf8_encoder from the initial work we did. My suggestion at the moment would probably be to remove this completely.
- We've introduced a basic Smpp::Transmitter (NOTE, this will need to be refactored based on your commit - https://github.com/raykrueger/ruby-smpp/commit/7f6c01efd857a202de76c803220aaa0521b67ea3).
- We've enhanced the UDH detection in Smpp::Pdu::DeliverSm. It can now correctly detect (as far as we can tell) UDHs containing both 8 and 16bit Concatenated SMS IDs.
- We tidied up some of the phone numbers in tests to use test data.
- We tidied up some of the tests so that by default they don't emit on STDOUT.

There is still work to do after the two forks have been merged: mainly refactor the duplication out of transmitter.rb and remove the encoding functionality completely.  I would prefer to sort these once the forks are in sync as it should be easier to make the changes in topic branches and issue smaller pull requests.

### CODE REVIEW

**Comment by crondaemon** [comment]
I'm going to user this code on a production SMSC. Can I provide some info to encourage the merge to the master?

**Comment by raykrueger** [comment]
Right now there are conflicts with the code in master. If someone can get that in sync I'll gladly merge it up.

**Comment by crondaemon** [comment]
I can try to branch and port. I will request a merge if I succeed.

**Comment by crondaemon** [comment]
I've done it. Hope it helps to have a working transmitter in current master.

**Comment by raykrueger** [comment]
@crondaemon did you have a pull request for this?

**Comment by crondaemon** [comment]
We've already merged it (issue #9). This is a dead one.

**Comment by raykrueger** [comment]
BOOSH! Thanks!

**Pull request closed without merging**
