### PR TITLE
Added transmitter support.

### PR DESCRIPTION
**Pull request by crondaemon**
Added support for transmitter starting from freerange fork. This merge takes into account the code restyle made in current master.

### CODE REVIEW

**Comment by crondaemon** [comment]
Any comment about the support? Can it be merged?

**Comment by raykrueger** [comment]
Sorry, just started a new job. Pretty busy. Is this in sync with the code in master? Github says it cannot be automatically merged.

**Comment by crondaemon** [comment]
I'm taking care of this.

**Comment by crondaemon** [comment]
Now code should be aligned to your master. Sorry I'm pretty new to git, I didn't notice the lack of alignment.

**Comment by crondaemon** [comment]
Hi,
is it ok now?

**Comment by crondaemon** [comment]
Hi Ray. Sorry for bothering you, you're busy, aren't you? I'm stressing to avoid this pull request to go to a dead end. Are you planning to merge it?

**Comment by raykrueger** [comment]
Looks good, thanks for the effort.
Don't stress, it's just code :)

**Pull request merged**
