### PR TITLE
Send deliver_sm_response to delivery receipts

### PR DESCRIPTION
**Pull request by cornet**
Unless I'm missing something here then on receiving a delivery receipt it should automatically send a deliver_sm_resp

### CODE REVIEW

**Comment by raykrueger** [comment]
Have you run into a problem here?
I think you're right that it's the appropriate response, but none of the aggregators seem to care that we're not sending it.

**Comment by cornet** [comment]
The aggregator I'm testing against does :)

**Comment by cornet** [comment]
Yes, sorry. Rogue debug line.

I should clarify that most aggregators I've delt with will queue delivery receipts and keep re-sending until you accept (or they expire them)

**Comment by raykrueger** [comment]
I'll come back to this, I've been drinking :)

**Comment by gshakir** [comment]
Hello,

We faced the same issue of dealing with delivery receipts. Can you please pull this changes on to the master ?

Thanks!
Gulam.

**Comment by raykrueger** [comment]
I've merged this and released 0.6.0.
Let me know if you see any problems. Sorry for the delay.

**Comment by gshakir** [comment]
Awesome. Thanks a lot and now we do not have to deal with our own customized gem!..:)

**Pull request merged**
