### PR TITLE
Callbacks for Invalid Username and Password

### PR DESCRIPTION
**Pull request by mcommons**
Hi,
I've made a small change to add callbacks for login errors. Our code will reconnect after a connection failure, but I find it useful to not do so in the case of a login failure causing the disconnect.

Thanks,
Mal

### CODE REVIEW

**Comment by raykrueger** [comment]
Thanks,
I'll have a look at it.

On Thu, Apr 21, 2011 at 9:42 AM, mcommons
reply@reply.github.com
wrote:

**Comment by crondaemon** [comment]
This is a very old one... I will take care of it: if it still applies, it can be merged,  otherwise I will patch the code myself.

**Comment by crondaemon** [comment]
A new branch [more_callbacks] have been created. It introduces a new way callbacks are called by the base class, that look smarter to me. Callbacks are also called when invalid password/system id or unknown error are received. 
@raykrueger from now and ahead I will create branches instead committing on master (unless they're trivial things) so you can have a look at my changes before merging into the master. Do you agree?

**Comment by raykrueger** [comment]
Pull requests would be great.

However, I wouldn't start a new branch just replicating the effort of this one. (P.S. I didn't look at the more_callbacks branch yet, if that's not what you've done). You can merge this work into it's own branch, or into the one you've created, and get it in sync with master. 

```
git checkout more_callbacks
git remote add mcommons https://github.com/mcommons/ruby-smpp.git
git fetch mcommons
git merge mcommons/master
```

Ideally we'd be working from a branch, for the sake of isolation, at mcommons rather than master. I don't see any unrelated commits after the pull request though so it should be fine.

**Comment by raykrueger** [comment]
This was merged into #20, which has been merged into master. Thanks for the help!

**Pull request closed without merging**
